version: "3"
services:
  web:
    image: btholt/node-app
    # change build to image as Kompose (as of writing) doesn't have a way to easily use local images without pushing it to Docker Hub
    ports:
      - "3000:3000"
    links:
      - db
    labels:
      kompose.service.type: LoadBalancer
      # need this label for k8 so it will expose this particular service to the outside world
    environment:
      MONGO_CONNECTION_STRING: mongodb://db:27017
  db:
    image: mongo:3
    ports:
      - "27017" # explicitly expose the port
